package io.github.blackbaroness.deluxemenusmodern;

import lombok.experimental.UtilityClass;
import org.bukkit.block.banner.PatternType;

@UtilityClass
public class LegacySupport {

    // On newer versions, PatternType is not an enum, it's an interface.
    // If we compile a PatternType.valueOf call with modern Paper API,
    // generated bytecode will be ABI incompatible with older versions like 1.18 and below.
    // We have to compile it with Paper 1.16 because of that.
    public PatternType resolvePatternType(String name) {
        return PatternType.valueOf(name);
    }
}
